<?php

/**
 * @file
 * Primary module hooks for Config Form Custom module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_element_info_alter().
 */
function config_form_custom_element_info_alter(array &$info) {
  $info['textfield']['#attached']['library'][] = 'config_form_custom/config_form_custom';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function config_form_custom_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'config_form_custom/config_form_custom';
}
