<?php

namespace Drupal\config_form_custom\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

/**
 * Class TestSettings.
 *
 * @package Drupal\config_form_custom\Form
 */
class TestSettingsForm extends ConfigFormBase {

  /**
   * {@inheritdoc}
   */
  public function getFormId() {
    // TODO: Implement getFormId() method.
    return 'config_form_custom_test_settings';
  }

  /**
   * {@inheritdoc}
   */
  public function getEditableConfigNames() {
    // TODO: Implement getEditableConfigNames() method.
    return ['config_form_custom.test_settings'];
  }

  /**
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state) {
    $form['name'] = [
      '#type' => 'textfield',
      '#title' => 'Name',
      '#default_value' => $this->config('config_form_custom.test_settings')->get('name'),
    ];

    $form['country'] = [
      '#type' => 'select',
      '#title' => 'Country',
      '#options' => [
        '1' => 'India',
        '2' => 'Pakistan',
      ],
      '#default_value' => $this->config('config_form_custom.test_settings')->get('country'),
    ];

    $form['gender'] = [
      '#type' => 'radios',
      '#title' => 'Gender',
      '#options' => [
        'male' => 'Male',
        'female' => 'Female',
      ],
      '#default_value' => $this->config('config_form_custom.test_settings')->get('gender'),
    ];

    // TODO: Change the autogenerated stub.
    return parent::buildForm($form, $form_state);
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    $config_settings = $this->config('config_form_custom.test_settings');
    $config_settings->set('name', $form_state->getValue('name'))->save();
    $config_settings->set('country', $form_state->getValue('country'))->save();
    $config_settings->set('gender', $form_state->getValue('gender'))->save();

    // TODO: Change the autogenerated stub.
    parent::submitForm($form, $form_state);

  }

}
